/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description What this instance can actually do right now.
         *
         *     ``status`` is derived rather than asserted. A readiness probe that returns
         *     ``ok`` with a dead database is not a probe, and Compose is configured to
         *     gate on this endpoint -- so a hard-coded ``ok`` would report every instance
         *     healthy including the ones that are not.
         *
         *     The dependencies are reported separately because they fail separately, and
         *     each disables a different part of the product: without Pandoc nothing
         *     exports, without GROBID nothing parses, without a model there is no review
         *     or editing. The UI reads these to disable what cannot work rather than
         *     letting a researcher discover it by clicking.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["list_papers_papers_get"];
        put?: never;
        /** Upload Paper */
        post: operations["upload_paper_papers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papers/{paper_id}/manuscript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Manuscript
         * @description The current revision's parsed content.
         *
         *     Separate from ``GET /papers/{id}`` because it is a different size of thing:
         *     the detail response is polled after every operation, and a whole manuscript
         *     does not belong in it.
         */
        get: operations["get_manuscript_papers__paper_id__manuscript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papers/{paper_id}/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Paper */
        post: operations["parse_paper_papers__paper_id__parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papers/{paper_id}/citation-style": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Citation Style
         * @description The researcher decides the style; detection only suggested one.
         *
         *     Not idempotency-keyed: PATCH with a literal value is naturally idempotent,
         *     and requiring a key for a preference toggle would be ceremony without safety.
         */
        patch: operations["set_citation_style_papers__paper_id__citation_style_patch"];
        trace?: never;
    };
    "/papers/{paper_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_papers__paper_id__reviews_get"];
        put?: never;
        /** Create Review */
        post: operations["create_review_papers__paper_id__reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_reviews__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Handle Finding
         * @description Mark one finding as dealt with, or put it back.
         *
         *     The finding stays in its run and in the run's counts.
         */
        patch: operations["handle_finding_findings__finding_id__patch"];
        trace?: never;
    };
    "/papers/{paper_id}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_papers__paper_id__proposals_get"];
        put?: never;
        /** Create Proposal */
        post: operations["create_proposal_papers__paper_id__proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{proposal_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept */
        post: operations["accept_proposals__proposal_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description Rejection is a state transition, and it is claimed like every other one.
         *
         *     Without a claim, a lost response followed by the client's retry answers
         *     with a state conflict rather than replaying the success it never saw --
         *     which reads to the researcher as though the rejection failed.
         */
        post: operations["reject_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papers/{paper_id}/export/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Preflight */
        get: operations["export_preflight_papers__paper_id__export_preflight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/papers/{paper_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Export */
        post: operations["create_export_papers__paper_id__exports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_exports__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{run_id}/artifacts/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Artifact */
        get: operations["download_artifact_exports__run_id__artifacts__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptProposalRequest */
        AcceptProposalRequest: {
            /** Acknowledged Warning Ids */
            acknowledged_warning_ids?: string[];
            /** Candidate Sha256 */
            candidate_sha256: string;
        };
        /** AcceptProposalResponse */
        AcceptProposalResponse: {
            /** Proposal Id */
            proposal_id: string;
            /** Revision Id */
            revision_id: string;
            /** Revision Number */
            revision_number: number;
        };
        /** ArtifactOut */
        ArtifactOut: {
            /** Name */
            name: string;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Href */
            href: string;
        };
        /**
         * BlockerCode
         * @description Things the system refuses to do, whatever the researcher says.
         * @enum {string}
         */
        BlockerCode: "PROTECTED_TOKEN_VIOLATION" | "CITATION_INVENTED" | "UNSUPPORTED_NOVELTY" | "ATTACHMENT_CONTRADICTED" | "NEW_CITATION_UNSUPPORTED" | "NEW_REFERENCE_INCOMPLETE" | "BLOCK_MUTATED" | "STRUCTURE_DAMAGED" | "PROSE_MUTATED" | "IDENTITY_INVARIANT_VIOLATED";
        /** BlockerOut */
        BlockerOut: {
            code: components["schemas"]["BlockerCode"];
            /** Message */
            message: string;
            /** Subject Ids */
            subject_ids?: string[];
        };
        /** Body_upload_paper_papers_post */
        Body_upload_paper_papers_post: {
            /** File */
            file: string;
            /** Filename */
            filename?: string | null;
        };
        /** ChangeOut */
        ChangeOut: {
            /** Kind */
            kind: string;
            /** Subject Id */
            subject_id: string;
            /** Related Ids */
            related_ids?: string[];
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * CheckName
         * @enum {string}
         */
        CheckName: "PROTECTED_TOKENS" | "CITATION_PRESERVATION" | "SEMANTIC_ATTACHMENT" | "SEMANTIC_NOVELTY" | "NEW_CITATION_SUPPORT" | "STRUCTURE_PRESERVATION" | "BLOCK_PRESERVATION" | "REFERENCE_COMPLETENESS" | "PROSE_IMMUTABILITY";
        /** CheckOut */
        CheckOut: {
            name: components["schemas"]["CheckName"];
            status: components["schemas"]["CheckStatus"];
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Model */
            model?: string | null;
            /** Model Provider */
            model_provider?: string | null;
        };
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "PASSED" | "WARNED" | "BLOCKED" | "NOT_RUN";
        /**
         * CitationStyle
         * @enum {string}
         */
        CitationStyle: "IEEE" | "APA";
        /** ClaimLocation */
        ClaimLocation: {
            /** Paragraph Id */
            paragraph_id: string;
            /** Sentence Id */
            sentence_id: string;
            /** Sentence Index */
            sentence_index: number;
            /** Section Id */
            section_id?: string | null;
            /** Section Title */
            section_title?: string | null;
            /** Text */
            text: string;
        };
        /** CreateExportRequest */
        CreateExportRequest: {
            /** Acknowledged Warning Ids */
            acknowledged_warning_ids?: string[];
        };
        /** CreateProposalRequest */
        CreateProposalRequest: {
            /** Command */
            command: string;
            /**
             * Section Id
             * @description Bind the command to this section instead of inferring one from the prose.
             */
            section_id?: string | null;
            /**
             * Paragraph Id
             * @description Bind the command to this paragraph. Narrows the edit to it alone.
             */
            paragraph_id?: string | null;
        };
        /** DegradationOut */
        DegradationOut: {
            /** Provider */
            provider: string;
            code: components["schemas"]["ErrorCode"];
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** DeltaOut */
        DeltaOut: {
            /** Changes */
            changes: components["schemas"]["ChangeOut"][];
            /** Words Before */
            words_before: number;
            /** Words After */
            words_after: number;
            /**
             * Scope Words Before
             * @default 0
             */
            scope_words_before: number;
            /**
             * Scope Words After
             * @default 0
             */
            scope_words_after: number;
            /** Summary */
            summary: string;
        };
        /**
         * EditScopeOut
         * @description Which part of the paper the command was resolved to, before it ran.
         */
        EditScopeOut: {
            /** Section Id */
            section_id: string;
            /**
             * Section Title
             * @default
             */
            section_title: string;
            /** Paragraph Id */
            paragraph_id?: string | null;
            /** Targeted Paragraph Ids */
            targeted_paragraph_ids?: string[];
            /** Skipped */
            skipped?: components["schemas"]["SkippedParagraphOut"][];
            /**
             * Words Before
             * @default 0
             */
            words_before: number;
            /**
             * Words Target
             * @default 0
             */
            words_target: number;
            /**
             * Section Paragraph Count
             * @default 0
             */
            section_paragraph_count: number;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "MALFORMED_REQUEST" | "UNSUPPORTED_FILE_TYPE" | "FILE_TOO_LARGE" | "NOT_FOUND" | "IDEMPOTENCY_KEY_REUSED" | "OPERATION_IN_PROGRESS" | "INVALID_STATE_TRANSITION" | "PROPOSAL_STATE_INVALID" | "STALE_REVISION" | "CANDIDATE_SNAPSHOT_MISMATCH" | "VERIFICATION_MISMATCH" | "ACKNOWLEDGEMENT_REQUIRED" | "OPERATION_TIMED_OUT" | "PARSER_UNAVAILABLE" | "PARSER_FAILED" | "TEI_MALFORMED" | "PROVIDER_RATE_LIMITED" | "PROVIDER_UNAVAILABLE" | "PROVIDER_NOT_FOUND" | "PROVIDER_INVALID_RESPONSE" | "PROVIDER_BUDGET_EXHAUSTED" | "NO_RESULTS" | "LLM_NOT_CONFIGURED" | "LLM_UNAVAILABLE" | "LLM_INVALID_OUTPUT" | "LLM_REFUSED" | "UNSUPPORTED_INTENT" | "AMBIGUOUS_INTENT" | "GROUNDING_VALIDATION_FAILED" | "PROTECTED_TOKEN_VIOLATION" | "UNSUPPORTED_NOVELTY" | "PROSE_MUTATION_FORBIDDEN" | "IDENTITY_INVARIANT_VIOLATED" | "CANDIDATE_CONSTRUCTION_FAILED" | "VERIFICATION_BLOCKED" | "EXPORT_BLOCKED" | "UNKNOWN_CITATION_STYLE" | "INVALID_ARTIFACT_NAME" | "EXPORT_NOT_READY" | "CITATION_RENDER_MISMATCH" | "RENDER_FAILED" | "INTERNAL_ERROR";
        /** ErrorDetail */
        ErrorDetail: {
            code: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * ErrorEnvelope
         * @description Every non-2xx response body. One shape, always.
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** EvidenceSpan */
        EvidenceSpan: {
            /** Source Record Id */
            source_record_id: string;
            /** Span Id */
            span_id: string;
            /** Text */
            text: string;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /**
         * ExportPreflight
         * @description What export will and will not be able to do, before it is started.
         *
         *     Blockers and acknowledgeable warnings are separate lists because they are
         *     different questions: one is "this cannot be done", the other is "this can be
         *     done at a cost you must accept".
         */
        ExportPreflight: {
            /** Revision Id */
            revision_id: string;
            citation_style: components["schemas"]["CitationStyle"] | null;
            /** Can Export */
            can_export: boolean;
            /** Blockers */
            blockers?: components["schemas"]["PreflightItem"][];
            /** Warnings */
            warnings?: components["schemas"]["WarningOut"][];
        };
        /** ExportRunOut */
        ExportRunOut: {
            /** Id */
            id: string;
            /** Paper Id */
            paper_id: string;
            /** Revision Id */
            revision_id: string;
            citation_style: components["schemas"]["CitationStyle"];
            status: components["schemas"]["RunStatus"];
            failure_code?: components["schemas"]["ErrorCode"] | null;
            /** Failure Detail */
            failure_detail?: string | null;
            /** Artifacts */
            artifacts?: components["schemas"]["ArtifactOut"][];
        };
        /**
         * FindingKind
         * @enum {string}
         */
        FindingKind: "CITATION_SUPPORT" | "UNCITED_CLAIM" | "MISSING_WORK" | "UNRESOLVED_REFERENCE" | "UNLINKED_CITATION";
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: string;
            kind: components["schemas"]["FindingKind"];
            verdict?: components["schemas"]["SupportVerdict"] | null;
            claim: components["schemas"]["ClaimLocation"];
            /** Occurrence Id */
            occurrence_id?: string | null;
            /** Reference Id */
            reference_id?: string | null;
            /** Reference Label */
            reference_label?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceSpan"][];
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Suggestions */
            suggestions?: components["schemas"]["SuggestedWork"][];
            /** Model Provider */
            model_provider?: string | null;
            /** Model */
            model?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /**
             * Handled
             * @default false
             */
            handled: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandleFindingRequest */
        HandleFindingRequest: {
            /** Handled */
            handled: boolean;
        };
        /**
         * InlineCitation
         * @description One citation occurrence, as the reader saw it and as the parser understood it.
         *
         *     ``raw_marker`` is what the author wrote and is always shown. The structured
         *     fields say how much of it was understood, so a marker the parser could only
         *     keep verbatim is visibly different from one it resolved -- rather than both
         *     rendering as confident-looking brackets.
         */
        InlineCitation: {
            /** Citation Id */
            citation_id: string;
            /** Raw Marker */
            raw_marker: string;
            /** Reference Ids */
            reference_ids?: string[];
            parse_status: components["schemas"]["SemanticParseStatus"];
            /**
             * Is Unlinked
             * @default false
             */
            is_unlinked: boolean;
            /**
             * Fidelity Exportable
             * @default true
             */
            fidelity_exportable: boolean;
        };
        /**
         * InlineRun
         * @description One span of a paragraph: prose, or a citation occurrence.
         */
        InlineRun: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "text" | "citation";
            /**
             * Text
             * @default
             */
            text: string;
            citation?: components["schemas"]["InlineCitation"] | null;
        };
        /**
         * ManuscriptOut
         * @description The parsed manuscript, in a shape built for reading rather than for storage.
         *
         *     Deliberately not the stored ``Document``: that carries preserved blocks,
         *     hashes, and per-item citation structure a reader has no use for, and shipping
         *     it would make the storage model a public contract that could not then be
         *     changed without breaking clients.
         */
        ManuscriptOut: {
            /** Paper Id */
            paper_id: string;
            /** Revision Id */
            revision_id: string;
            /** Revision Number */
            revision_number: number;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Abstract
             * @default
             */
            abstract: string;
            /** Sections */
            sections?: components["schemas"]["SectionOut"][];
            /** References */
            references?: components["schemas"]["ReferenceOut"][];
            /** Unlinked Citation Ids */
            unlinked_citation_ids?: string[];
            /** Raw Only Citation Ids */
            raw_only_citation_ids?: string[];
        };
        /**
         * NormalizationStatus
         * @enum {string}
         */
        NormalizationStatus: "COMPLETE" | "PARTIAL" | "RAW_ONLY";
        /** PaperDetail */
        PaperDetail: {
            /** Id */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["PaperStatus"];
            failure_code?: components["schemas"]["ErrorCode"] | null;
            citation_style?: components["schemas"]["CitationStyle"] | null;
            detected_citation_style?: components["schemas"]["CitationStyle"] | null;
            detected_style_confidence?: components["schemas"]["StyleConfidence"] | null;
            /** Current Revision Id */
            current_revision_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            parse_quality?: components["schemas"]["ParseQuality"] | null;
            /** Detected Style Reason */
            detected_style_reason?: string | null;
            /**
             * Revision Count
             * @default 0
             */
            revision_count: number;
        };
        /**
         * PaperStatus
         * @enum {string}
         */
        PaperStatus: "UPLOADED" | "PARSING" | "PARSED" | "PARSE_FAILED" | "DELETING";
        /** PaperSummary */
        PaperSummary: {
            /** Id */
            id: string;
            /** Original Filename */
            original_filename: string;
            /** Title */
            title: string | null;
            status: components["schemas"]["PaperStatus"];
            failure_code?: components["schemas"]["ErrorCode"] | null;
            citation_style?: components["schemas"]["CitationStyle"] | null;
            detected_citation_style?: components["schemas"]["CitationStyle"] | null;
            detected_style_confidence?: components["schemas"]["StyleConfidence"] | null;
            /** Current Revision Id */
            current_revision_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ParagraphDiff */
        ParagraphDiff: {
            /** Paragraph Id */
            paragraph_id: string;
            /** Section Id */
            section_id?: string | null;
            /** Before Text */
            before_text: string;
            /** After Text */
            after_text: string;
            /** Before Citation Ids */
            before_citation_ids?: string[];
            /** After Citation Ids */
            after_citation_ids?: string[];
        };
        /** ParagraphOut */
        ParagraphOut: {
            /** Id */
            id: string;
            /** Order Index */
            order_index: number;
            /** Inlines */
            inlines?: components["schemas"]["InlineRun"][];
            /**
             * Word Count
             * @default 0
             */
            word_count: number;
        };
        /**
         * ParseQuality
         * @description What the parse got, and what it did not.
         *
         *     Surfaced before any review or edit, because a researcher deciding whether to
         *     trust this tool needs the extraction's limits stated up front rather than
         *     discovered at export.
         */
        ParseQuality: {
            /** Sections */
            sections: number;
            /** Paragraphs */
            paragraphs: number;
            /** Words */
            words: number;
            citations: components["schemas"]["ParseQualityCitations"];
            references: components["schemas"]["ParseQualityReferences"];
            blocks: components["schemas"]["ParseQualityBlocks"];
            linkage?: components["schemas"]["ParseQualityLinkage"] | null;
            /**
             * Bibliography Retained
             * @default true
             */
            bibliography_retained: boolean;
        };
        /** ParseQualityBlocks */
        ParseQualityBlocks: {
            /** Total */
            total: number;
            /** By Kind */
            by_kind: {
                [key: string]: number;
            };
            /** Unrenderable */
            unrenderable: number;
            /** Unrenderable Ids */
            unrenderable_ids: string[];
            /** Floating */
            floating: number;
        };
        /** ParseQualityCitations */
        ParseQualityCitations: {
            /** Total */
            total: number;
            /** Linked */
            linked: number;
            /** Unlinked */
            unlinked: number;
            /** Raw Only */
            raw_only: number;
            /** Partial Modifiers */
            partial_modifiers: number;
            /** Clusters */
            clusters: number;
        };
        /**
         * ParseQualityLinkage
         * @description How marker-to-bibliography linkage held up under independent checking.
         *
         *     ``checked`` is the honest denominator: items where a second, unrelated signal
         *     existed at all. Reporting accuracy over every item would quietly count
         *     unverifiable ones as successes.
         */
        ParseQualityLinkage: {
            /** Family */
            family: string;
            /** Checked */
            checked: number;
            /** Agreed */
            agreed: number;
            /** Mismatched */
            mismatched: number;
            /** Recovered */
            recovered: number;
            /** Ambiguous */
            ambiguous: number;
            /** Unresolved */
            unresolved: number;
            /** Uncertain */
            uncertain: number;
            /** Accuracy */
            accuracy: number;
            /** Downgraded */
            downgraded: number;
            /** Promoted */
            promoted: number;
        };
        /** ParseQualityReferences */
        ParseQualityReferences: {
            /** Total */
            total: number;
            /** Complete */
            complete: number;
            /** Partial */
            partial: number;
            /** Raw Only */
            raw_only: number;
        };
        /** PreflightItem */
        PreflightItem: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Subject Ids */
            subject_ids?: string[];
        };
        /** ProposalOut */
        ProposalOut: {
            /** Id */
            id: string;
            /** Paper Id */
            paper_id: string;
            /** Base Revision Id */
            base_revision_id: string;
            /** Command */
            command: string;
            /** Intent */
            intent?: string | null;
            state: components["schemas"]["ProposalState"];
            failure_code?: components["schemas"]["ErrorCode"] | null;
            /** Failure Detail */
            failure_detail?: string | null;
            /** Candidate Sha256 */
            candidate_sha256?: string | null;
            delta?: components["schemas"]["DeltaOut"] | null;
            /** Checks */
            checks?: components["schemas"]["CheckOut"][];
            /** Blockers */
            blockers?: components["schemas"]["BlockerOut"][];
            /** Warnings */
            warnings?: components["schemas"]["WarningOut"][];
            /** Required Warning Ids */
            required_warning_ids?: string[];
            /**
             * Explanation
             * @default
             */
            explanation: string;
            scope?: components["schemas"]["EditScopeOut"] | null;
            /** Diffs */
            diffs?: components["schemas"]["ParagraphDiff"][];
        };
        /**
         * ProposalState
         * @enum {string}
         */
        ProposalState: "PENDING" | "AWAITING_DECISION" | "BLOCKED" | "ACCEPTED" | "REJECTED" | "FAILED" | "SUPERSEDED";
        /**
         * ReferenceOut
         * @description One bibliography entry, in the state the pipeline left it.
         *
         *     Normalisation status and resolution method travel with the entry because a
         *     reference that is present but unresolved supports a different kind of trust
         *     than one matched to a provider record by DOI.
         */
        ReferenceOut: {
            /** Id */
            id: string;
            /** Bibliography Order */
            bibliography_order: number;
            /** Title */
            title?: string | null;
            /** Authors */
            authors?: string[];
            /** Year */
            year?: number | null;
            /** Container Title */
            container_title?: string | null;
            /** Doi */
            doi?: string | null;
            /** Url */
            url?: string | null;
            /**
             * Raw Text
             * @default
             */
            raw_text: string;
            normalization_status: components["schemas"]["NormalizationStatus"];
            resolution_method: components["schemas"]["ResolutionMethod"];
            resolution_confidence: components["schemas"]["ResolutionConfidence"];
            /** Source Record Id */
            source_record_id?: string | null;
            /**
             * Occurrences
             * @default 0
             */
            occurrences: number;
        };
        /**
         * ResolutionConfidence
         * @description Confidence is read off observable evidence, never asserted by a model.
         * @enum {string}
         */
        ResolutionConfidence: "CERTAIN" | "PROBABLE" | "UNCERTAIN" | "NONE";
        /**
         * ResolutionMethod
         * @description How a reference was matched to a provider record, strongest first.
         * @enum {string}
         */
        ResolutionMethod: "DOI" | "ARXIV" | "PUBMED" | "EXTERNAL_ID" | "TITLE_AUTHOR_YEAR" | "TITLE_ONLY" | "UNRESOLVED";
        /** ReviewRunOut */
        ReviewRunOut: {
            /** Id */
            id: string;
            /** Paper Id */
            paper_id: string;
            /** Revision Id */
            revision_id: string;
            status: components["schemas"]["RunStatus"];
            failure_code?: components["schemas"]["ErrorCode"] | null;
            /** Degradations */
            degradations?: components["schemas"]["DegradationOut"][];
            /** Stats */
            stats?: {
                [key: string]: unknown;
            };
            /** Findings */
            findings?: components["schemas"]["FindingOut"][];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "PENDING" | "COMPLETED" | "FAILED";
        /** SectionOut */
        SectionOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Level
             * @default 1
             */
            level: number;
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Paragraphs */
            paragraphs?: components["schemas"]["ParagraphOut"][];
        };
        /**
         * SemanticParseStatus
         * @description How much of the marker the parser actually understood.
         * @enum {string}
         */
        SemanticParseStatus: "STRUCTURED" | "PARTIAL_MODIFIERS" | "RAW_ONLY";
        /** SetCitationStyleRequest */
        SetCitationStyleRequest: {
            citation_style: components["schemas"]["CitationStyle"];
        };
        /** SkippedParagraphOut */
        SkippedParagraphOut: {
            /** Paragraph Id */
            paragraph_id: string;
            /** Reason */
            reason: string;
        };
        /**
         * StyleConfidence
         * @enum {string}
         */
        StyleConfidence: "HIGH" | "LOW" | "UNKNOWN";
        /**
         * SuggestedWork
         * @description A work the manuscript does not cite, as the provider described it.
         *
         *     Every field is read from the snapshotted ``source_records`` row, so a
         *     suggestion the researcher cannot look up cannot be rendered. ``rationale``
         *     is the only model-authored string here and is labelled as interpretation.
         */
        SuggestedWork: {
            /** Source Record Id */
            source_record_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors?: string[];
            /** Year */
            year?: number | null;
            /** Venue */
            venue?: string | null;
            /** Doi */
            doi?: string | null;
            /** Url */
            url?: string | null;
            /** Provider */
            provider: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /**
         * SupportVerdict
         * @description Whether a cited work supports the claim it is attached to.
         *
         *     ``UNSUPPORTED`` is deliberately absent. Failing to find support in an
         *     abstract is not evidence that the cited paper lacks it -- the material may
         *     be in the full text -- and reporting it as unsupported would launder absence
         *     of evidence into a finding against the researcher's citation. Every verdict
         *     is an abstract-level assessment and is labelled as one.
         * @enum {string}
         */
        SupportVerdict: "SUPPORTED" | "PARTIALLY_SUPPORTED" | "CONTRADICTED" | "UNVERIFIABLE_FROM_AVAILABLE_EVIDENCE" | "EVIDENCE_UNAVAILABLE" | "SOURCE_IDENTITY_UNCERTAIN" | "SOURCE_UNRESOLVED";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarningCode
         * @description Consequences a researcher can knowingly accept.
         * @enum {string}
         */
        WarningCode: "CITATION_REMOVED" | "REFERENCE_LEFT_UNCITED" | "ATTACHMENT_INVALIDATED" | "NEW_CITATION_PARTIAL_SUPPORT" | "NEW_CITATION_SOURCE_UNCERTAIN" | "TARGET_NOT_MET" | "PROVIDER_DEGRADED" | "FIDELITY_LOSS";
        /** WarningOut */
        WarningOut: {
            /** Id */
            id: string;
            code: components["schemas"]["WarningCode"];
            /** Message */
            message: string;
            /** Subject Ids */
            subject_ids?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_papers_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSummary"][];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    upload_paper_papers_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_paper_papers_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSummary"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_paper_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_manuscript_papers__paper_id__manuscript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManuscriptOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    parse_paper_papers__paper_id__parse_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    set_citation_style_papers__paper_id__citation_style_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCitationStyleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_reviews_papers__paper_id__reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunOut"][];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_review_papers__paper_id__reviews_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_review_reviews__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewRunOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    handle_finding_findings__finding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandleFindingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_proposals_papers__paper_id__proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"][];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_proposal_papers__paper_id__proposals_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_proposal_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    accept_proposals__proposal_id__accept_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptProposalResponse"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    reject_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    export_preflight_papers__paper_id__export_preflight_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportPreflight"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_export_papers__paper_id__exports_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRunOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_export_exports__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRunOut"];
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    download_artifact_exports__run_id__artifacts__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
